{% set name = "classify-imports" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/classify_imports-{{ version }}.tar.gz
  sha256: 7abfb7ea92149b29d046bd34573d247ba6e68cc28100c801eba4af17964fc40e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - classify_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asottile/classify-imports
  summary: Utilities for refactoring imports in python-like syntax.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - MattChanTK
